<?xml version="1.0" encoding="UTF-8"?>
<testrun name="InternalStorageWrapperTest.testLoadFromStorage_TryToLoadNotSavedFileFromStorage_ObjectIsNull" project="ContraceptiveTimerTest" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest" time="99.952">
    <testcase name="testLoadFromStorage_TryToLoadNotSavedFileFromStorage_ObjectIsNull" classname="ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest" time="99.952">
      <failure>junit.framework.AssertionFailedError&#13;
at ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest.testLoadFromStorage_TryToLoadNotSavedFileFromStorage_ObjectIsNull(InternalStorageWrapperTest.java:71)&#13;
at java.lang.reflect.Method.invokeNative(Native Method)&#13;
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)&#13;
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)&#13;
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)&#13;
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1575)&#13;

</failure>
    </testcase>
  </testsuite>
</testrun>
